version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:v2Y/RPBQ6J/xDnTYoIuCZnZCptOOZhPOjC9yY30wvzI=
      - APP_URL=http://localhost:8000
      - BACKEND_URL=http://backend:8001
    depends_on:
      - backend
    volumes:
      - ./frontend/storage:/var/www/html/storage
      - ./frontend/bootstrap/cache:/var/www/html/bootstrap/cache

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - RAG_URL=http://rag:8002
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - rag
    volumes:
      - ./backend:/app

  rag:
    build: ./rag
    ports:
      - "8002:8002"
    volumes:
      - ./rag/chroma_db:/app/chroma_db
      - ./rag/docs_oficiales:/app/docs_oficiales

networks:
  default:
    name: uvoxdata_network
