services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:v2Y/RPBQ6J/xDnTYoIuCZnZCptOOZhPOjC9yY30wvzI=
      - APP_URL=http://localhost:8000
      - BACKEND_URL=http://backend:8001
      - SESSION_DRIVER=file
    depends_on:
      - backend
    volumes:
        - ./frontend:/var/www/html
        - frontend_vendor:/var/www/html/vendor
        - frontend_node:/var/www/html/node_modules

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - RAG_URL=http://rag:8002
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - rag
    volumes:
      - ./backend:/app

  rag:
    build: ./rag
    ports:
      - "8002:8002"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-llama-3.3-70b-versatile}
    volumes:
      - ./rag/chroma_db:/app/chroma_db
      - ./rag/docs_oficiales:/app/docs_oficiales

networks:
  default:
    name: uvoxdata_network

volumes:
  frontend_vendor:
  frontend_node: